### PR TITLE
Run PHPStan on previous major version of PS

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
This PR allows PHPStan to run on two versions of PrestaShop 1.6, covering now all the compatibility range.

:warning: Some pull-requests must be merged first:
* https://github.com/PrestaShopCorp/ps_checkout/pull/311
* https://github.com/PrestaShop/php-dev-tools/pull/23 (With a new release published, or some classes will remain not found)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Looks like the version 0.12.20 triggers issues on our builds

**Comment by Matt75** [comment]
@Quetzacoalt91 This PR should be rebased

**Comment by Quetzacoalt91** [comment]
Rebase done

**Comment by Matt75** [comment]
Thanks you @Quetzacoalt91

**Pull request merged**
