### PR TITLE
Fix preselected payment method

### PR DESCRIPTION
**Pull request by Matt75**

### CODE REVIEW

**Review by PSebou — APPROVED** [review]

**Review by btafforeau — APPROVED** [review]

**Comment by beforcom** [comment]
Hi, 
In my version 2.21.0 I can't found the files : _dev/js/front/src/components/1_6/payment-options.component.js 
i want to Fix preselected payment method.
If I download version 3.1.0 it's not compatible with my Prestashop version 1.7.4.2
What can I do please ?
Regards

**Comment by btafforeau** [comment]
Hello,

You can download the 2.21.0 **source code** (not the build version) from GitHub Release page : https://github.com/PrestaShopCorp/ps_checkout/releases/tag/v2.21.0.

Do not put it directly on your server. You need to edit the file **_dev/js/front/src/components/1_7/payment-options.component.js** and add the line to fix preselected payment method.

Then, you need to generate the front.js file by calling the command **npm run build --prefix ./_dev/js/front**
Make sure to make a copy of your existing front.js on your server before replacing it by the new generated one.

You can now check that the fix is working. Don't forget to clean your cache.

**Comment by btafforeau** [comment]
Hello,

You can download the 2.21.0 **source code** (not the build version) from GitHub Release page : https://github.com/PrestaShopCorp/ps_checkout/releases/tag/v2.21.0.

Do not put it directly on your server. You need to edit the file **_dev/js/front/src/components/1_7/payment-options.component.js** and add the line to fix preselected payment method.

Then, you need to generate the front.js file by calling the command **npm run build --prefix ./_dev/js/front**
Make sure to make a copy of your existing front.js on your server before replacing it by the new generated one.

You can now check that the fix is working. Don't forget to clean your cache.

> Hi, In my version 2.21.0 I can't found the files : _dev/js/front/src/components/1_6/payment-options.component.js i want to Fix preselected payment method. If I download version 3.1.0 it's not compatible with my Prestashop version 1.7.4.2 What can I do please ? Regards

**Comment by beforcom** [comment]
Thanks,
I do not understand this step : 
"Then, you need to generate the front.js file by calling the command npm run build --prefix ./_dev/js/front"
How can I do this ?
Regards

**Comment by Alpi-Web** [comment]
Hi, did you find the solution to call the command ?
Thanks

**Comment by beforcom** [comment]
Thank you for your message. I still don't know how to run this command. The update fixing this problem was supposed to be released 15 days ago. For now the fix is ​​only available for prestashop 8 but not yet for prestashop 1.7. I am waiting for the release of the new version on 1.7. Anyone have a release date?
THANKS

**Pull request merged**
