### PR TITLE
Release v8.4.2.1

### PR DESCRIPTION
**Pull request by Matt75**

### CODE REVIEW

**Comment by riyantowibowo** [comment]
Hi @Matt75 excuse me for comment in here, I just installed Prestashop Checkout module but it said pending validation all the time even though PayPal said you're all set. [Someone from PayPal said](https://www.paypal-community.com/t5/PayPal-Payments-Standard/Connect-PayPal-account/td-p/3082964) that you have grant third party permission, but it must insert the username to grant it and I don't know what the third party username of Prestashop Checkout module?

I have write this in forum as well, for more details; 
https://www.prestashop.com/forums/topic/1089721-prestashop-checkout-pending-validation-for-paypal-account-connect/

Thank you in advance

**Comment by Matt75** [comment]
> Hi @Matt75 excuse me for comment in here, I just installed Prestashop Checkout module but it said pending validation all the time even though PayPal said you're all set. [Someone from PayPal said](https://www.paypal-community.com/t5/PayPal-Payments-Standard/Connect-PayPal-account/td-p/3082964) that you have grant third party permission, but it must insert the username to grant it and I don't know what the third party username of Prestashop Checkout module?
> 
> I have write this in forum as well, for more details; https://www.prestashop.com/forums/topic/1089721-prestashop-checkout-pending-validation-for-paypal-account-connect/
> 
> Thank you in advance

Hello @riyantowibowo 

I'm sorry but I cannot help here.

Could you create a support ticket from the configuration page of the module, at the bottom of the help section, you have a link `Contact us` after `Couldn't find any answer to your question?`.

Thanks

**Comment by riyantowibowo** [comment]
> > Hi @Matt75 excuse me for comment in here, I just installed Prestashop Checkout module but it said pending validation all the time even though PayPal said you're all set. [Someone from PayPal said](https://www.paypal-community.com/t5/PayPal-Payments-Standard/Connect-PayPal-account/td-p/3082964) that you have grant third party permission, but it must insert the username to grant it and I don't know what the third party username of Prestashop Checkout module?
> > I have write this in forum as well, for more details; https://www.prestashop.com/forums/topic/1089721-prestashop-checkout-pending-validation-for-paypal-account-connect/
> > Thank you in advance
> 
> Hello @riyantowibowo
> 
> I'm sorry but I cannot help here.
> 
> Could you create a support ticket from the configuration page of the module, at the bottom of the help section, you have a link `Contact us` after `Couldn't find any answer to your question?`.
> 
> Thanks

Hi @Matt75

It looks like I've found a solution to the problem. Thanks for creating such a great module!

**Comment by cdigruttola** [comment]
Good morning,

when is planned the release 8.4.2.1? The old one 8.4.2.0 is causing error on Prestashop 8.2 

mod_fcgid: stderr: PHP Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, PrestaShop\\PrestaShop\\Adapter\\Presenter\\Cart\\CartLazyArray given in ps_checkout\src\Presenter\Cart\CartPresenter.php:62

**Comment by ang3lx** [comment]
same problem here ( @cdigruttola ) 
incompatibility with prestashop 8.2 and ps_checkout (new CartLazyArray breaks the site)
Prestashop 8.2 is a security update at the moment, and ps_checkout (that is official module) is not already capable with it.
Bad management...

**Pull request merged**
