### PR TITLE
refactor(ps_accounts): v4 integration

### PR DESCRIPTION
**Pull request by hschoenenberger**

### CODE REVIEW

**Comment by seiwan** [comment]
We are implementing PS Accounts V5 in PS Checkout. This PR is no more useless.

**Comment by smithikakart** [comment]
<PsAccounts> integration: Given context is invalid: "shops[1].shops[0].domain" must be a string

Facing the above error 

Prestashop version is : 1.7.6.4
php version is : 7.2
apche+nginx server
PS_accounts version is : V 5.0.0

**Comment by Alcpaone** [comment]
After Modul update to new Version 5.1 still same error:

<PsAccounts> integration: Given context is invalid: "shops[1].shops[0].domain" must be a string

PS Version: 1.7.6.5
php Version: 7.3.22
PS_Account Module is 5.1
Multishop: yes

**Comment by smithikakart** [comment]
Yes facing same issue any one help us to fix this issue

Regards Smithikakart.<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
